#!/bin/bash

VERCEL_TOKEN="PuXWTsv0m2YQYRhHqPKVBINJ"
NEXTAUTH_SECRET=$(openssl rand -base64 32)

echo "🔑 Настройка GitHub Secrets вручную"
echo "===================================="
echo ""

echo "📋 Готовые значения для копирования:"
echo "===================================="
echo ""
echo "🔐 VERCEL_TOKEN:"
echo "$VERCEL_TOKEN"
echo ""
echo "🔐 NEXTAUTH_SECRET:"
echo "$NEXTAUTH_SECRET"
echo ""
echo "🔐 NEXTAUTH_URL:"
echo "https://ma-platform.vercel.app"
echo ""

echo "🔗 Открываю GitHub Secrets..."
open "https://github.com/AlexSevryuga/ma-platform/settings/secrets/actions"

echo ""
echo "📝 Инструкция по добавлению секретов:"
echo "====================================="
echo ""
echo "1. На странице GitHub Secrets нажмите 'New repository secret'"
echo "2. Добавьте следующие секреты:"
echo ""
echo "   Имя: VERCEL_TOKEN"
echo "   Значение: $VERCEL_TOKEN"
echo ""
echo "   Имя: NEXTAUTH_SECRET"
echo "   Значение: $NEXTAUTH_SECRET"
echo ""
echo "   Имя: NEXTAUTH_URL"
echo "   Значение: https://ma-platform.vercel.app"
echo ""
echo "3. Также добавьте:"
echo "   Имя: OPENAI_API_KEY"
echo "   Значение: ваш_ключ_openai"
echo ""
echo "4. После создания проекта на Vercel добавьте:"
echo "   Имя: VERCEL_ORG_ID"
echo "   Значение: ваш_org_id"
echo ""
echo "   Имя: VERCEL_PROJECT_ID"
echo "   Значение: ваш_project_id"
echo ""

echo "🚀 Следующие шаги:"
echo "=================="
echo "1. Добавьте секреты в GitHub (ссылка открыта выше)"
echo "2. Перейдите на https://vercel.com/new"
echo "3. Импортируйте репозиторий: AlexSevryuga/ma-platform"
echo "4. Настройте переменные окружения в Vercel"
echo "5. Нажмите 'Deploy'"
echo ""

echo "✅ После этого автоматический деплой будет работать!" 