#!/bin/bash

echo "🚀 Быстрая настройка деплоя на Vercel"
echo "======================================"

# Генерируем NEXTAUTH_SECRET
NEXTAUTH_SECRET=$(openssl rand -base64 32)
echo "🔑 Сгенерирован NEXTAUTH_SECRET:"
echo "$NEXTAUTH_SECRET"
echo ""

echo "📋 Готовые значения для настройки:"
echo "=================================="
echo "NEXTAUTH_SECRET: $NEXTAUTH_SECRET"
echo "NEXTAUTH_URL: https://ma-platform.vercel.app (замените на реальный URL после деплоя)"
echo "OPENAI_API_KEY: (ваш ключ OpenAI)"
echo "DATABASE_URL: (опционально, если используете базу данных)"
echo ""

echo "🔗 Открываю необходимые ссылки..."
echo ""

# Открываем ссылки
open "https://vercel.com/new"
open "https://github.com/AlexSevryuga/ma-platform"
open "https://github.com/AlexSevryuga/ma-platform/settings/secrets/actions"
open "https://vercel.com/account/tokens"

echo "📝 Пошаговая инструкция:"
echo "========================"
echo ""
echo "1️⃣ Создание проекта на Vercel:"
echo "   - На странице Vercel выберите 'Import Git Repository'"
echo "   - Выберите репозиторий: AlexSevryuga/ma-platform"
echo "   - Нажмите 'Import'"
echo ""
echo "2️⃣ Настройка переменных окружения:"
echo "   - В разделе 'Environment Variables' добавьте:"
echo "     • NEXTAUTH_SECRET: $NEXTAUTH_SECRET"
echo "     • NEXTAUTH_URL: https://your-app-name.vercel.app"
echo "     • OPENAI_API_KEY: ваш_ключ_openai"
echo "     • DATABASE_URL: ваш_url_базы_данных (опционально)"
echo ""
echo "3️⃣ Первый деплой:"
echo "   - Нажмите 'Deploy'"
echo "   - Дождитесь завершения сборки"
echo "   - Запишите URL вашего приложения"
echo ""
echo "4️⃣ Настройка автоматического деплоя:"
echo "   - Перейдите в https://vercel.com/account/tokens"
echo "   - Создайте новый токен"
echo "   - Получите ORG_ID и PROJECT_ID из настроек проекта"
echo "   - Добавьте в GitHub Secrets:"
echo "     • VERCEL_TOKEN: ваш_vercel_токен"
echo "     • VERCEL_ORG_ID: ваш_org_id"
echo "     • VERCEL_PROJECT_ID: ваш_project_id"
echo ""
echo "5️⃣ Обновление NEXTAUTH_URL:"
echo "   - После деплоя обновите NEXTAUTH_URL на реальный URL"
echo "   - Обновите переменную в Vercel и GitHub Secrets"
echo ""
echo "✅ После этого каждый push в main будет автоматически деплоить приложение!"
echo ""
echo "🔧 Если нужна помощь с настройкой, проверьте файл VERCEL_DEPLOYMENT_GUIDE.md" 