#!/bin/bash

echo "🚀 Упрощенная настройка деплоя M&A AI Platform"
echo "=============================================="
echo ""

echo "📋 Инструкция по настройке Vercel:"
echo ""
echo "1. 🔗 Откройте Vercel Dashboard:"
echo "   https://vercel.com/new"
echo ""
echo "2. 🔗 Подключите GitHub репозиторий:"
echo "   https://github.com/AlexSevryuga/ma-platform"
echo ""
echo "3. ⚙️  Настройте проект:"
echo "   - Framework Preset: Next.js"
echo "   - Root Directory: ./"
echo "   - Build Command: npm run build"
echo "   - Output Directory: .next"
echo ""
echo "4. 🔧 Добавьте переменные окружения:"
echo "   NEXTAUTH_URL=https://your-project.vercel.app"
echo "   NEXTAUTH_SECRET=$(openssl rand -base64 32)"
echo "   OPENAI_API_KEY=sk-demo-key"
echo ""
echo "5. 🚀 Нажмите Deploy"
echo ""

# Открываем ссылки
echo "🔗 Открываю ссылки в браузере..."
open "https://vercel.com/new"
open "https://github.com/AlexSevryuga/ma-platform"

echo ""
echo "✅ После настройки Vercel:"
echo "   1. Ваше приложение будет доступно по адресу:"
echo "      https://your-project.vercel.app"
echo ""
echo "   2. Настройте GitHub Integration в Vercel Dashboard"
echo ""
echo "   3. Добавьте переменные окружения в GitHub Secrets:"
echo "      https://github.com/AlexSevryuga/ma-platform/settings/secrets/actions"
echo ""
echo "🔧 Автоматические действия:"
echo "   - GitHub Actions будут запускаться при каждом push"
echo "   - Автоматический деплой при merge в main"
echo "   - Тестирование и линтинг"
echo ""

echo "🎯 Готово! Следуйте инструкциям выше для завершения настройки." 